apiVersion: v1
kind: Service
metadata:
  name: testserver
spec:
  selector:
    app: testserver
  ports:
    - port: 3000
      targetPort: 3000
#      nodePort: 30001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testserver
  template:
    metadata:
      labels:
        app: testserver
    spec:
      containers:
        - name: testserver
          image: testserver:v1
          ports:
            - containerPort: 3000
          env:
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /usr/src/data
              name: testserver-volume
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
      volumes:
        - name: testserver-volume
          hostPath:
            path: /home/craig/testserver
            type: Directory
