apiVersion: v1
kind: Service
metadata:
  name: otherserver
spec:
  selector:
    app: otherserver
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30002
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otherserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otherserver
    template:
      metadata:
        labels:
          app: otherserver
      spec:
        containers:
          - name: otherserver
            image: otherserver:v1
            ports:
              - containerPort: 3001
            imagePullPolicy: Never
            livenessProbe:
              httpGet:
                path: /healthcheck
                port: 3001